# <div align="center">REALISATION D'UN TEST STATISTIQUE D'ESTIMATION DE LA MOYENNE AVEC SCIPY</div>

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ttest_1samp as ttest1

In [22]:
data=pd.read_csv("ecoles-creches-idf.csv")
data.head()

,ID,nom,departement,ville,CP,type,NO2_2012,NO2_2013,NO2_2014,NO2_2015,...,PM10_2015,PM10_2016,PM10_2017,PM25_2012,PM25_2013,PM25_2014,PM25_2015,PM25_2016,PM25_2017,geometry
0,0750026W,L'Enseignement par petits groupes (Ecole secon...,75,Paris 15,75015,secondaire,41.316912,42.916257,40.610102,37.182711,...,23.790138,23.077844,21.782889,17.152857,18.637080,14.895546,15.277787,14.806532,13.549347,"c(2.2908106734441, 48.8421565600018)"
1,0750106H,Ecole technologique privée CCIP Centre des For...,75,Paris 20,75020,secondaire,63.683878,60.890328,53.322156,45.804898,...,26.063983,23.803116,23.020608,22.692531,23.629341,18.628494,16.978740,15.434943,14.429643,"c(2.40580700033425, 48.8756657433978)"
2,0750132L,Ecole primaire privée Notre-Dame-Saint Roch,75,Paris 01,75001,primaire,41.507336,41.598420,42.855147,39.286859,...,22.995246,22.400441,20.867075,16.614189,18.142261,14.487745,14.562495,14.134427,12.561472,"c(2.33270615799049, 48.8661396641722)"
3,0750136R,Ecole primaire privée Saint-Sauveur,75,Paris 02,75002,primaire,45.197342,44.280198,45.187931,40.855468,...,23.650961,23.405547,22.650735,17.713481,19.089383,15.433904,15.067306,14.756645,15.118740,"c(2.34734689771536, 48.8668886093452)"
4,0750138T,Ecole primaire privée Sainte Geneviève du Marais,75,Paris 03,75003,primaire,40.109546,39.257252,39.688121,37.249166,...,22.808231,22.049934,20.717201,16.332941,17.645253,14.270936,14.391215,13.911639,12.654443,"c(2.36480092620121, 48.8569700986785)"

In [23]:
data.shape

(12530, 25)

# PROCEDURE DE L'ANALYSE


### -Stocker les données d'emissions de NO2 de 2012 à 2016 dans une dataframe df1.
### -Stocker les données d'emissions de NO2 en 2017 dans une dataframe df2.
### -Calculer les moyennes **m1** et **m2** des deux echantillons.
### -Mise en place des hypotheses:
    -H0: il n'y a pas de difference entre les deux moyennes.
    -H1: il y a une difference significative entre les deux moyennes.
### -Faire le test ttest1de scipy.stats ttest_1samp en inserant df2.val et m1 et lire la valeur de statistic et pvalue. 
####       -Si p_value<0.05 ==>On peut rejetter H0.
####       -Si P_value>0.05 ==>On peut maintenir H0.